version: '3.9'

services:
  app:
    image: openjdk:17-jre-slim
    container_name: youtube_sharing_app
    ports:
      - "8080:8080"
    build:
      context: . # Use the current directory as the build context
      dockerfile: Dockerfile # Specify a Dockerfile in the same directory
    volumes:
      - .:/app
    working_dir: /app
    command: ["java", "-jar", "target/YouTubeSharingApp-0.0.1-SNAPSHOT.jar"]
    depends_on:
      - db
    networks:
      - tuho-network
    environment:
      - spring.jpa.hibernate.ddl-auto=update
      - spring.datasource.url=jdbc:mysql://youtube_sharing_db:3306/youtube_sharing
      - spring.datasource.username=user
      - spring.datasource.password=password
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver



  db:
    image: mysql:8
    container_name: youtube_sharing_db
    environment:
      MYSQL_DATABASE: youtube_sharing
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"
    expose:
      - "3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - tuho-network

volumes:
  mysql_data:

networks:
  tuho-network:
    driver: bridge
